name: build docker images for release
on: 
  push:
    branches:
      - main

env: 
  IMAGE_BACKEND_NAME: 'test-app'
  APP_BACKEND_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Register variables
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup QEMU for docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ${{ env.APP_BACKEND_PATH }}
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_BACKEND_NAME }}:latest
          push: true

      - name: Output metadata
        run: echo ${{ steps.docker_build.outputs.* }}
        
  trigger-cd:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add text
      run: echo "test" > test.txt
    - name: switching from HTTPS to SSH
      run: git remote set-url origin https://github.com/RasmusWiktellSundman/argocd-test.git
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating test.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to main
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
